theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag
title: "beau.sh"
tagline: "Beau Bouchard's lil' site"
description: "A collection of Beau Bouchard’s weird web projects"
social:
  name: Beau Bouchard
  links:
    - https://www.linkedin.com/in/beaubouchard
    - https://github.com/beaubouchard
    - https://mastodon.social/@beaubouchard
    - https://bsky.app/profile/beaubouchard.bsky.social
url: beau.sh
